# Generated by Django 4.0.6 on 2022-08-03 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('card_id', models.CharField(db_index=True, default=None, max_length=20)),
            ],
        ),
    ]
